name: Build Apps Cucala

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-13, macos-14]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Este passo termina aqui. O próximo passo deve ter a mesma indentação.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      # CORREÇÃO: Este passo "- name:" está agora corretamente indentado.
      - name: Build Consolidador
        run: pyinstaller --noconfirm consolidador.spec

      # CORREÇÃO: Este passo "- name:" também está corretamente indentado.
      - name: Build Gerenciador
        run: pyinstaller --noconfirm gerenciador.spec

      - name: Package Consolidador
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            powershell Compress-Archive -Path dist/Consolidador CUCALA/* -DestinationPath dist/consolidador-${{ runner.os }}.zip
          else
            tar -czvf dist/consolidador-${{ runner.os }}.tar.gz -C dist/Consolidador CUCALA .
          fi

      - name: Package Gerenciador
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            powershell Compress-Archive -Path dist/Gerenciador CUCALA/* -DestinationPath dist/gerenciador-${{ runner.os }}.zip
          else
            tar -czvf dist/gerenciador-${{ runner.os }}.tar.gz -C dist/Gerenciador CUCALA .
          fi

      - name: Upload Consolidador
        uses: actions/upload-artifact@v4
        with:
          name: Consolidador-${{ runner.os }}
          path: |
            dist/consolidador-*.zip
            dist/consolidador-*.tar.gz

      - name: Upload Gerenciador
        uses: actions/upload-artifact@v4
        with:
          name: Gerenciador-${{ runner.os }}
          path: |
            dist/gerenciador-*.zip
            dist/gerenciador-*.tar.gz