```yaml
name: Build and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'arm64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        # Usa versão mais recente do PyInstaller, a menos que 6.3.0 seja necessário
        pip install --no-cache-dir pyinstaller

    - name: Build executables
      run: |
        # Gera executáveis com os novos .spec
        pyinstaller --clean --noconfirm consolidador(1).spec
        pyinstaller --clean --noconfirm gerenciador(1).spec
        # Verifica se os .app foram gerados
        ls -la dist/*.app || { echo "Erro: .app não encontrados!"; exit 1; }
        echo "Pausing for 5 seconds to stabilize file system..."
        sleep 5

    - name: Create DMG
      run: |
        # Instala create-dmg
        brew install create-dmg

        # Cria DMG para Consolidador
        create-dmg \
          --volname "Consolidador" \
          --volicon "assets/icon.icns" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "Consolidador.app" 200 190 \
          --hide-extension "Consolidador.app" \
          --app-drop-link 600 185 \
          "dist/Consolidador.dmg" \
          "dist/Consolidador.app"
        
        echo "Pausing for 5 seconds to prevent resource busy errors..."
        sleep 5

        # Cria DMG para Gerenciador
        create-dmg \
          --volname "Gerenciador" \
          --volicon "assets/icon.icns" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "Gerenciador.app" 200 190 \
          --hide-extension "Gerenciador.app" \
          --app-drop-link 600 185 \
          "dist/Gerenciador.dmg" \
          "dist/Gerenciador.app"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-apps-arm64
        path: |
          dist/*.app
          dist/*.dmg
        retention-days: 7

    - name: Create release (on tag)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/Consolidador.dmg
          dist/Gerenciador.dmg
        draft: false
        prerelease: false
        generate_release_notes: true
```
