name: Build Executables

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --prefer-binary -r requirements.txt

    - name: Build executables
      run: |
        if [ "${{ matrix.os }}" = "Windows" ]; then
          pyinstaller --noconfirm consolidador.spec
          pyinstaller --noconfirm gerenciador.spec
        else
          pyinstaller --noconfirm consolidador.spec
          pyinstaller --noconfirm gerenciador.spec
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: |
          dist/**
