name: Build and Package (Intel)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir pyinstaller==6.3.0

      - name: Build executables
        run: |
          pyinstaller --clean --noconfirm consolidador.spec
          pyinstaller --noconfirm gerenciador.spec
          echo "Listing generated .app files:"
          ls -la dist/*.app || { echo "Error: .app files not found!"; exit 1; }
          echo "Pausing for 10 seconds to stabilize file system..."
          sleep 10

      - name: Rename .app bundles
        run: |
          mv "dist/Consolidador.app" "dist/Consolidador-intel.app"
          mv "dist/Gerenciador.app" "dist/Gerenciador-intel.app"
          echo "Listing renamed .app files:"
          ls -la dist/*-intel.app || { echo "Error: Renamed .app files not found!"; exit 1; }
          echo "Pausing for 10 seconds to stabilize file system..."
          sleep 10

      - name: Create DMG
        run: |
          brew install create-dmg
          rm -f dist/*.dmg
          echo "Creating DMG for Consolidador..."
          for attempt in {1..3}; do
            if create-dmg \
              --volname "Consolidador" \
              --volicon "assets/icon.icns" \
              --window-pos 200 120 \
              --window-size 800 400 \
              --icon-size 100 \
              --icon "Consolidador-intel.app" 200 190 \
              --hide-extension "Consolidador-intel.app" \
              --app-drop-link 600 185 \
              "dist/Consolidador-intel.dmg" \
              "dist/Consolidador-intel.app"; then
              echo "DMG for Consolidador created successfully."
              break
            else
              echo "Attempt $attempt failed for Consolidador. Retrying after 5 seconds..."
              sleep 5
            fi
          done
          echo "Pausing for 5 seconds..."
          sleep 5
          echo "Creating DMG for Gerenciador..."
          for attempt in {1..3}; do
            if create-dmg \
              --volname "Gerenciador" \
              --volicon "assets/icon.icns" \
              --window-pos 200 120 \
              --window-size 800 400 \
              --icon-size 100 \
              --icon "Gerenciador-intel.app" 200 190 \
              --hide-extension "Gerenciador-intel.app" \
              --app-drop-link 600 185 \
              "dist/Gerenciador-intel.dmg" \
              "dist/Gerenciador-intel.app"; then
              echo "DMG for Gerenciador created successfully."
              break
            else
              echo "Attempt $attempt failed for Gerenciador. Retrying after 5 seconds..."
              sleep 5
            fi
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-apps-intel
          path: |
            dist/*-intel.app
            dist/*-intel.dmg
          retention-days: 7

      - name: Create release (on tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/Consolidador-intel.dmg
            dist/Gerenciador-intel.dmg
          draft: false
          prerelease: false
          generate_release_notes: true
```
